version: '3.8'

services:
  app:
    build:
      context: .  # Location of the Dockerfile
    container_name: rewardhub_app
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    volumes:
      - ./logs:/RewardHub/logs  # Optional: Mount logs for persistent storage
